<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class HypersignPluginAPISetting {
	private $hypersign_plugin_api_setting_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'hypersign_plugin_api_setting_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'hypersign_plugin_api_setting_page_init' ) );
	}

	public function hypersign_plugin_api_setting_add_plugin_page() {
		add_options_page(
			'Hypersign API', // page_title
			'Hypersign API', // menu_title
			'manage_options', // capability
			'hypersign-plugin-api-setting', // menu_slug
			array( $this, 'hypersign_plugin_api_setting_create_admin_page' ) // function
		);
	}

	public function hypersign_plugin_api_setting_create_admin_page() {
		$this->hypersign_plugin_api_setting_options = get_option( 'hypersign_plugin_api_setting_option_name' ); ?>

		<div class="wrap">
			<h2>Hypersign API Setting</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'hypersign_plugin_api_setting_option_group' );
					do_settings_sections( 'hypersign-plugin-api-setting-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function hypersign_plugin_api_setting_page_init() {
		register_setting(
			'hypersign_plugin_api_setting_option_group', // option_group
			'hypersign_plugin_api_setting_option_name', // option_name
			array( $this, 'hypersign_plugin_api_setting_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'hypersign_plugin_api_setting_setting_section', // id
			'Enter AppId and AppSecret generated from developer dashboard', // title
			array( $this, 'hypersign_plugin_api_setting_section_info' ), // callback
			'hypersign-plugin-api-setting-admin' // page
		);

		add_settings_field(
			'app_id_0', // id
			'App Id', // title
			array( $this, 'app_id_0_callback' ), // callback
			'hypersign-plugin-api-setting-admin', // page
			'hypersign_plugin_api_setting_setting_section' // section
		);

		add_settings_field(
			'app_secret_1', // id
			'App Secret', // title
			array( $this, 'app_secret_1_callback' ), // callback
			'hypersign-plugin-api-setting-admin', // page
			'hypersign_plugin_api_setting_setting_section' // section
		);
	}

	public function hypersign_plugin_api_setting_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['app_id_0'] ) ) {
			$sanitary_values['app_id_0'] = sanitize_text_field( $input['app_id_0'] );
		}

		if ( isset( $input['app_secret_1'] ) ) {
			$sanitary_values['app_secret_1'] = sanitize_text_field( $input['app_secret_1'] );
		}

		return $sanitary_values;
	}

	public function hypersign_plugin_api_setting_section_info() {
		
	}

	public function app_id_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="hypersign_plugin_api_setting_option_name[app_id_0]" id="app_id_0" value="%s">',
			isset( $this->hypersign_plugin_api_setting_options['app_id_0'] ) ? esc_attr( $this->hypersign_plugin_api_setting_options['app_id_0']) : ''
		);
	}

	public function app_secret_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="hypersign_plugin_api_setting_option_name[app_secret_1]" id="app_secret_1" value="%s">',
			isset( $this->hypersign_plugin_api_setting_options['app_secret_1'] ) ? esc_attr( $this->hypersign_plugin_api_setting_options['app_secret_1']) : ''
		);
	}

}
if ( is_admin() )
	$hypersign_plugin_api_setting = new HypersignPluginAPISetting();

/* 
 * Retrieve this value with:
 * $hypersign_plugin_api_setting_options = get_option( 'hypersign_plugin_api_setting_option_name' ); // Array of All Options
 * $app_id_0 = $hypersign_plugin_api_setting_options['app_id_0']; // App Id
 * $app_secret_1 = $hypersign_plugin_api_setting_options['app_secret_1']; // App Secret
 */
